#change this
footprint: [[0.16, 0.15],
            [0.16, 0.147],
            [0.17, 0.147],
            [0.17, -0.147],
            [0.16, -0.147],
            [0.16, -0.15],
            [-0.17, -0.15],
            [-0.17, 0.15]]

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.25
footprint_padding: 0.03

