#Independent settings for the planner's costmap
global_costmap:
    publish_voxel_map: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 2.0
    static_map: true
    rolling_window: false
